MVCMultiLayerProject/Controllers/WriterPanelContentController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCMultiLayerProject.Controllers
{
    [Authorize(Roles = "writer")]
    public class WriterPanelContentController : Controller
    {
        ContentManager cmr = new ContentManager(new EFContentDAL());
        HeadingManager hm = new HeadingManager(new EFHeadingDAL());
        Context c = new Context();
        // GET: WriterPanelContent
        public ActionResult Index(string p)
        {
            p = (string)Session["AdminUserName"];
            var writeridinfo = c.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterID).FirstOrDefault();
            TempData["writeridid"] = writeridinfo;
            ViewBag.writername = c.Writers.Where(x => x.WriterMail == p).Select(w => w.WriterName).FirstOrDefault();
            ViewBag.writersurname = c.Writers.Where(x => x.WriterMail == p).Select(w => w.WriterSurname).FirstOrDefault();
            ViewBag.writerimage = c.Writers.Where(x => x.WriterMail == p).Select(i => i.WriterImage).FirstOrDefault();
            TempData["writerName"] = ViewBag.writername;
            TempData["writerSurname"] = ViewBag.writersurname;
            TempData["writerImage"] = ViewBag.writerimage;
            var contentvalues = cmr.GetListByWriter(writeridinfo);
            return View(contentvalues);
        }
        [HttpGet]
        public ActionResult WPContentUpdate(int id)
        {
            var contentvalue = cmr.GetByID(id);
            return View(contentvalue);
        }
        [HttpPost]
        public ActionResult WPContentUpdate(Content p)
        {
            cmr.ContentUpdate(p);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult WPContentAdd()
        {
            List<SelectListItem> valueheading = (from x in hm.GetList() // DÜZELT
                                                 select new SelectListItem
                                                 {
                                                     Text = x.HeadingName,
                                                     Value = x.HeadingID.ToString()
                                                 }).ToList();
            ViewBag.vlh = valueheading; //DÜZELTİLECEK
            return View();
        }
        [HttpPost]
        public ActionResult WPContentAdd(Content p)
        {
            p.ContentDate = DateTime.Parse(DateTime.Now.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss"));
            p.ContentStatus = true;
            p.WriterID = (int)TempData["writeridid"];
            Content newcontent = new Content();
            newcontent.ContentImage = p.ContentImage;
            newcontent.ContentValue = p.ContentValue;
            newcontent.HeadingID = p.HeadingID;
            newcontent.ContentStatus = p.ContentStatus;
            newcontent.ContentDate = p.ContentDate;
            newcontent.WriterID = p.WriterID;
            cmr.ContentAdd(newcontent);
            return RedirectToAction("Index");
        }
        public ActionResult WPContentByHeader(int id)
        {
            var wpcontentvalue = cmr.GetListByHeadingID(id);
            return View(wpcontentvalue);
        }
    }
}

MVCMultiLayerProject/Views/WriterPanelContent/Index.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

@{ string color = "";
    string bttn = "";
    string status = ""; }

<body class="hold-transition sidebar-mini">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Yazarın Yazıları</h1>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="card">
            <div class="card-header">
                Yazarın Tüm Yazıları
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>
            <br />
            <div class="wrapper">
                <section class="content">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                                @foreach (var x in Model)
                                {
                                    if (x.ContentStatus && x.Heading.HeadingStatus && x.Heading.Category.CategoryStatus == true && x.WriterID == x.Writer.WriterID)
                                    {
                                        color = "badge badge-success";
                                    }
                                    else
                                    {
                                        color = "badge badge-danger";
                                    }
                                    <div class="timeline">

                                        <div class="time-label">
                                            <span class="bg-success">@(((DateTime)x.ContentDate).ToString("dd.MMM.yyyy"))</span>
                                        </div>
                                        <div>
                                            <i class="fas fa-comment bg-yellow"></i>
                                            <div class="timeline-item">
                                                <h3 class="timeline-header">
                                                    <a href="/Home/BlogDetay/@x.ContentID">@x.Heading.HeadingName</a> @x.Writer.WriterName @x.Writer.WriterSurname
                                                    <a href="/WriterPanelContent/WPContentUpdate/@x.ContentID" class="btn btn-success">Yazıyı Düzenle</a>
                                                    <a class="@color">Yazı Durumu</a>
                                                </h3>
                                                <div class="timeline-body">
                                                    <img src="@x.ContentImage" style="max-width: 725px; max-height: 430px;" />
                                                    <br />
                                                    @x.ContentValue
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </section>
    </br>
    </br>
    <a href="/WriterPanelContent/WPContentAdd/" class="btn btn-primary">Yeni Yazı Ekle</a>
</body>

MVCMultiLayerProject/Views/WriterPanelContent/WPContentAdd.cshtml
@model EntityLayer.Concrete.Content
@{
    ViewBag.Title = "WPContentAdd";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<body class="hold-transition sidebar-mini">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Yeni Yazı Ekleme Sayfası</h1>
                </div>
            </div>
        </div>
    </section>

    @using (Html.BeginForm("WPContentAdd", "WriterPanelContent", FormMethod.Post))
    {
<div class="form-group">
    @Html.HiddenFor(x => x.ContentDate, new { @class = "form-control" })
    @Html.HiddenFor(x => x.Heading.Writer.WriterID, new { @class = "form-control" })
    @Html.HiddenFor(x => x.ContentStatus, new { @class = "form-control" })
    <br />
    @Html.Label("Başlık: ")
    @Html.DropDownListFor(x => x.HeadingID, (IEnumerable<SelectListItem>)ViewBag.vlh, new { @class = "form-control" })
    <br />
    @Html.Label("Yazı Resmi: ")
    @Html.TextAreaFor(x => x.ContentImage, new { @class = "form-control" })
    <br />
    @Html.Label("Yazı: ")
    @Html.TextAreaFor(x => x.ContentValue, new { @class = "form-control" })
    <script>
        CKEDITOR.replace('ContentValue');
    </script>
    <br />
    <button class="btn btn-default">Yeni Yazı Ekle</button>
</div>
    }
    @Scripts.Render("~/Scripts/jquery-1.7.1.min.js")
    @Scripts.Render("~/ckeditor/ckeditor.js")
    @Scripts.Render("~/ckeditor/ckfinder/ckfinder.js")
    @Scripts.Render("~/Scripts/jquery.validate.js")
    </body>

MVCMultiLayerProject/Views/WriterPanelContent/WPContentByHeader.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "WPContentByHeader";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        @foreach (var x in Model)
                        {
                            if (x.Heading.WriterID == x.WriterID) //Her yazar kendi başlığına yazı ekleyebilir.
                            {
                                <div class="timeline">

                                    <div class="time-label">
                                        <span class="bg-success">@(((DateTime)x.ContentDate).ToString("dd.MMM.yyyy"))</span>
                                    </div>
                                    <div>
                                        <i class="fas fa-comment bg-yellow"></i>
                                        <div class="timeline-item">
                                            <h3 class="timeline-header"><a href="#">@x.Heading.HeadingName</a> @x.Writer.WriterName @x.Writer.WriterSurname</h3>
                                            <div class="timeline-body">
                                                <img src="@x.ContentImage" style="max-width: 725px; max-height: 430px;" />
                                                <br />
                                                @x.ContentValue
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>

MVCMultiLayerProject/Views/WriterPanelContent/WPContentUpdate.cshtml
@model EntityLayer.Concrete.Content
@{
    ViewBag.Title = "WPContentUpdate";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<body class="hold-transition sidebar-mini">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>İçerik Güncelleme Sayfası</h1>
                </div>
            </div>
        </div>
    </section>
    
    @using (Html.BeginForm("WPContentUpdate", "WriterPanelContent", FormMethod.Post))
    {
        <div class="form-group">
            @Html.HiddenFor(x => x.ContentID, new { @class = "form-control" })
            @Html.HiddenFor(x => x.ContentDate, new { @class = "form-control" })
            @Html.HiddenFor(x => x.HeadingID, new { @class = "form-control" })
            @Html.HiddenFor(x => x.WriterID, new { @class = "form-control" })
            <br />
            @Html.Label("Yazı Durumu: ")
            @Html.TextAreaFor(x => x.ContentStatus, new { @class = "form-control" })
            <br />
            @Html.Label("Yazı: ")
            @Html.TextAreaFor(x => x.ContentValue, new { @class = "form-control" })
            <br />
            @Html.Label("Yazı Resmi: ")
            @Html.TextAreaFor(x => x.ContentImage, new { @class = "form-control" })
            <br />
            <button class="btn btn-success">Kaydet</button>
        </div>
    }