MVCMultiLayerProject/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCMultiLayerProject.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EFCategoryDAL());
        HeadingManager hm = new HeadingManager(new EFHeadingDAL());
        WriterManager wm = new WriterManager(new EFWriterDAL());
        // GET: AdminCategory
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var categoryvalues = cm.GetList();
            return View(categoryvalues);
        }
        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Category p)
        {

            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult results = categoryValidator.Validate(p);
            if (results.IsValid)
            {
                cm.CategoryAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var x in results.Errors)
                {
                    ModelState.AddModelError(x.PropertyName, x.ErrorMessage);
                }

            }
            return View();
        }
        public ActionResult DeleteCategory(int id)
        {
            var categoryvalue = cm.GetByID(id);
            cm.CategoryDelete(categoryvalue);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult UpdateCategory(int id)
        {
            var categoryvalue = cm.GetByID(id);
            return View(categoryvalue);
        }
        [HttpPost]
        public ActionResult UpdateCategory(Category p)
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult results = categoryValidator.Validate(p);
            if (results.IsValid)
            {
                cm.CategoryUpdate(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var x in results.Errors)
                {
                    ModelState.AddModelError(x.PropertyName, x.ErrorMessage);
                }
            }
            return View();
        }
        public ActionResult ChangeCategoryStatus(int id)
        {
            var categoryvalue = cm.GetByID(id);
            if(categoryvalue.CategoryStatus == false)
            {
                categoryvalue.CategoryStatus = true;
            }
            else
            {
                categoryvalue.CategoryStatus = false;
            }
            cm.CategoryUpdate(categoryvalue);
            return RedirectToAction("Index");
        }
    }
}

MVCMultiLayerProject/Views/AdminCategory/AddCategory.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<h1>Yeni Kategori Ekleme Sayfası</h1>

@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori Adı:")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br /> <br />
        @Html.Label("Kategori Açıklaması:")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription)
        <br /> <br />
        <button class="btn btn-default">Kategori Ekle</button>
    </div>
}

@*<form class="form-group" method="post">
        <input type="text" placeholder="Kategori Adı" name="CategoryName" class="form-control" />
        <br />
        <input type="text" placeholder="Açıklama" name="CategoryDescription" class="form-control" />
        <br />
        <button class="btn btn-primary">Ekle</button>
    </form>*@

MVCMultiLayerProject/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>

@{ ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml"; }

@{ string color = "";
    string bttn = "";
    string status = ""; }

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Kategoriler</h1>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="card">
            <div class="card-header">
                Kategori Tablosu
                <div class="card-tools" style="align-items:end">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr class="text-center">
                            <th style="width: 5%">
                                #
                            </th>
                            <th style="width: 20%">
                                Kategori Adı
                            </th>
                            <th style="width: 10%">
                                Kategori Durumu
                            </th>
                            <th style="width: 20%">
                                Kategori Açıklaması
                            </th>
                            <th style="width: 15%">
                                Ayarlar
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var x in Model)
                        {
                            if (x.CategoryStatus == true)
                            {
                                color = "badge badge-success";
                                bttn = "Pasif Yap";
                                status = "btn btn-danger btn-sm";
                            }
                            else
                            {
                                color = "badge badge-danger";
                                bttn = "Aktif Yap";
                                status = "btn btn-success btn-sm";
                            }
                            <tr class="text-center">
                                <td>
                                    @x.CategoryID
                                </td>
                                <td>
                                    <a>
                                        @x.CategoryName
                                    </a>
                                    <br />
                                </td>
                                <td class="project-state">
                                    <span class="@color">@x.CategoryStatus</span>
                                </td>
                                <td>
                                    <a>
                                        @x.CategoryDescription
                                    </a>
                                </td>
                                <td class="project-actions text-right" style="text-align:center!important">
                                    <a class="@status" href="/AdminCategory/ChangeCategoryStatus/@x.CategoryID">
                                        <i class="fa fa-refresh" aria-hidden="true"></i>
                                        @bttn
                                    </a>
                                    <a class="btn btn-success btn-sm" href="/Heading/HeadingsByCategory/@x.CategoryID">
                                        <i class="fas fa-book"></i>
                                        Kategoriye Ait Başlıklar
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/AdminCategory/UpdateCategory/@x.CategoryID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Güncelle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/AdminCategory/DeleteCategory/@x.CategoryID">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
}
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</body>
</html>
<a href="/AdminCategory/AddCategory/" class="btn btn-primary">Yeni Kategori Ekle</a>


@*<h2>Index</h2>
    <br />
    <table class="table table-bordered">
        <tr>
            <th>ID</th>
            <th>Başlık</th>
            <th>Kategori</th>
        </tr>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.HeadingID</td>
                <td>@item.HeadingName</td>
                <td>@item.Category.CategoryName</td>
            </tr>
        }
    </table>
    <br />
    <a href="/Heading/AddHeading" class="btn btn-info">Yeni başlık Girişi</a>*@

MVCMultiLayerProject/Views/AdminCategory/UpdateCategory.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewBag.Title = "UpdateCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Kategori Güncelleme Sayfası</h2>

@using (Html.BeginForm("UpdateCategory", "AdminCategory", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.CategoryID)
    @Html.Label("Kategori Adı")
    @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CategoryName)
    <br />
    @Html.Label("Kategori Açıklaması")
    @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CategoryDescription)
    <br />
    @Html.Label("Kategori Durumu")
    @Html.TextBoxFor(x => x.CategoryStatus, new { @class = "form-control" })
    <br/>
    <button class="btn btn-success">Kaydet</button>
</div>
}